from typing import Iterator, overload

import pyvrp
from pyvrp._pyvrp import (
    Activity,
    ActivityType,
    CostEvaluator,
    DurationSegment,
    LoadSegment,
    ProblemData,
    RandomNumberGenerator,
)

class OperatorPerformance:
    """
    Tracks the performance of a local search operator for adaptive operator
    selection using the Multi-Armed Bandit (UCB) algorithm.

    Uses Exponentially Weighted Moving Average (EWMA) for avgReward, which
    gives more weight to recent performance and allows dynamic adaptation.
    """

    total_reward: float
    """Cumulative reward (cost improvements) from this operator (for statistics)."""

    selection_count: int
    """Number of times this operator was selected (placed first in order)."""

    application_count: int
    """Number of times this operator successfully applied an improving move."""

    avg_reward: float
    """EWMA average reward (used for UCB calculation)."""

    alpha: float
    """Learning rate for EWMA (default 0.1). Higher = more weight to recent rewards."""

    def __init__(self) -> None: ...

    def update(self, reward: float, applied: bool) -> None:
        """
        Updates the performance metrics with a new reward.

        Parameters
        ----------
        reward
            The reward (cost improvement) achieved.
        applied
            Whether the operator was successfully applied.
        """
        ...

    def compute_ucb(
        self, total_selections: int, exploration_factor: float = 1.414
    ) -> float:
        """
        Computes the Upper Confidence Bound (UCB1) value for this operator.

        Parameters
        ----------
        total_selections
            Total number of selections across all operators.
        exploration_factor
            Exploration parameter (c in UCB formula). Default is sqrt(2).

        Returns
        -------
        float
            The UCB value.
        """
        ...

    def success_rate(self) -> float:
        """
        Returns the success rate of this operator.

        Returns
        -------
        float
            The ratio of applications to selections (in range [0, 1]).
        """
        ...

    def set_alpha(self, alpha: float) -> None:
        """
        Sets the learning rate (alpha) for EWMA.

        Parameters
        ----------
        alpha
            Learning rate in range [0, 1]. Higher values give more weight
            to recent rewards (faster adaptation).
            - 0.05: Very stable, slow adaptation
            - 0.1:  Default, balanced
            - 0.2:  Fast adaptation
            - 0.5:  Very reactive
        """
        ...

    def reset(self) -> None:
        """Resets all performance metrics to initial state."""
        ...

    def __eq__(self, other: OperatorPerformance) -> bool: ...

class OperatorStatistics:
    num_evaluations: int
    num_applications: int

class UnaryOperator:
    def __init__(self, data: ProblemData) -> None: ...
    @property
    def statistics(self) -> OperatorStatistics: ...
    def evaluate(
        self,
        U: Node,
        cost_evaluator: CostEvaluator,
    ) -> tuple[int, bool]: ...
    def apply(self, U: Node) -> None: ...
    def init(self, solution: Solution) -> None: ...
    @staticmethod
    def supports(data: ProblemData) -> bool: ...

class BinaryOperator:
    def __init__(self, data: ProblemData) -> None: ...
    @property
    def statistics(self) -> OperatorStatistics: ...
    def evaluate(
        self, U: Node, V: Node, cost_evaluator: CostEvaluator
    ) -> tuple[int, bool]: ...
    def apply(self, U: Node, V: Node) -> None: ...
    def init(self, solution: Solution) -> None: ...
    @staticmethod
    def supports(data: ProblemData) -> bool: ...

class RemoveAdjacentDepot(UnaryOperator): ...
class RemoveOptional(UnaryOperator): ...
class ReplaceGroup(UnaryOperator): ...
class InsertOptional(BinaryOperator): ...
class ReplaceOptional(BinaryOperator): ...
class Exchange10(BinaryOperator): ...
class Exchange11(BinaryOperator): ...
class Exchange20(BinaryOperator): ...
class Exchange21(BinaryOperator): ...
class Exchange22(BinaryOperator): ...
class Exchange30(BinaryOperator): ...
class Exchange31(BinaryOperator): ...
class Exchange32(BinaryOperator): ...
class Exchange33(BinaryOperator): ...
class RelocateWithDepot(BinaryOperator): ...
class SwapTails(BinaryOperator): ...

class SearchSpace:
    def __init__(
        self,
        data: ProblemData,
        neighbours: list[list[int]],
    ) -> None: ...
    @property
    def neighbours(self) -> list[list[int]]: ...
    @neighbours.setter
    def neighbours(self, neighbours: list[list[int]]) -> None: ...
    def neighbours_of(self, client: int) -> list[int]: ...
    def is_promising(self, client: int) -> bool: ...
    @overload
    def mark_promising(self, client: int) -> None: ...
    @overload
    def mark_promising(self, node: Node) -> None: ...
    def mark_all_promising(self) -> None: ...
    def unmark_all_promising(self) -> None: ...
    def client_order(self) -> list[int]: ...
    def veh_type_order(self) -> list[tuple[int, int]]: ...
    def shuffle(self, rng: RandomNumberGenerator) -> None: ...

class PerturbationParams:
    min_perturbations: int
    max_perturbations: int
    def __init__(
        self,
        min_perturbations: int = 1,
        max_perturbations: int = 25,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...

class PerturbationManager:
    def __init__(
        self,
        params: PerturbationParams = ...,
    ) -> None: ...
    def num_perturbations(self) -> int: ...
    def shuffle(self, rng: RandomNumberGenerator) -> None: ...
    def perturb(
        self,
        solution: Solution,
        search_space: SearchSpace,
        cost_evaluator: CostEvaluator,
    ) -> None: ...

class LocalSearchStatistics:
    num_moves: int
    num_improving: int
    num_updates: int

class LocalSearch:
    def __init__(
        self,
        data: ProblemData,
        neighbours: list[list[int]],
        perturbation_manager: PerturbationManager = ...,
    ) -> None: ...
    def add_operator(self, op: UnaryOperator | BinaryOperator) -> None: ...
    @property
    def neighbours(self) -> list[list[int]]: ...
    @neighbours.setter
    def neighbours(self, neighbours: list[list[int]]) -> None: ...
    @property
    def unary_operators(self) -> list[UnaryOperator]: ...
    @property
    def binary_operators(self) -> list[BinaryOperator]: ...
    @property
    @property
    def statistics(self) -> LocalSearchStatistics: ...
    def __call__(
        self,
        solution: pyvrp.Solution,
        cost_evaluator: CostEvaluator,
        exhaustive: bool = False,
    ) -> pyvrp.Solution: ...
    def shuffle(self, rng: RandomNumberGenerator) -> None: ...
    def set_exploration_factor(self, factor: float) -> None:
        """
        Sets the exploration factor for UCB algorithm.

        Parameters
        ----------
        factor
            Exploration parameter (c in UCB formula). Higher values encourage
            more exploration. Default is sqrt(2) ≈ 1.414.
        """
        ...

    def get_exploration_factor(self) -> float:
        """
        Gets the exploration factor for UCB algorithm.

        Returns
        -------
        float
            The current exploration factor.
        """
        ...

    @property
    def unary_performance(self) -> list[OperatorPerformance]:
        """
        Returns the performance statistics for all unary operators.

        Returns
        -------
        list[OperatorPerformance]
            Performance metrics for each unary operator, in the same order
            as they were added.
        """
        ...

    @property
    def binary_performance(self) -> list[OperatorPerformance]:
        """
        Returns the performance statistics for all binary operators.

        Returns
        -------
        list[OperatorPerformance]
            Performance metrics for each binary operator, in the same order
            as they were added.
        """
        ...

    def reset_operator_performance(self) -> None:
        """
        Resets all operator performance statistics to initial state.
        """
        ...

    def set_operator_alpha(self, alpha: float) -> None:
        """
        Sets the EWMA learning rate (alpha) for all operators.

        Parameters
        ----------
        alpha
            Learning rate in range [0, 1]. Higher values give more weight
            to recent performance (faster adaptation).
            - 0.05: Very stable, slow adaptation
            - 0.1:  Default, balanced
            - 0.2:  Fast adaptation
            - 0.5:  Very reactive
        """
        ...

class Solution:
    nodes: list[Node]
    routes: list[Route]
    def __init__(self, data: ProblemData) -> None: ...
    def load(self, solution: pyvrp.Solution) -> None: ...
    def unload(self) -> pyvrp.Solution: ...
    def insert(
        self,
        node: Node,
        search_space: SearchSpace,
        cost_evaluator: CostEvaluator,
        required: bool,
    ) -> bool: ...

class Route:
    def __init__(self, data: ProblemData, vehicle_type: int) -> None: ...
    @property
    def vehicle_type(self) -> int: ...
    def num_clients(self) -> int: ...
    def num_depots(self) -> int: ...
    def num_trips(self) -> int: ...
    def max_trips(self) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    def __delitem__(self, idx: int) -> None: ...
    def __getitem__(self, idx: int) -> Node: ...
    def __iter__(self) -> Iterator[Node]: ...
    def __len__(self) -> int: ...
    def is_feasible(self) -> bool: ...
    def has_excess_load(self) -> bool: ...
    def has_excess_distance(self) -> bool: ...
    def has_time_warp(self) -> bool: ...
    def capacity(self) -> list[int]: ...
    def start_depot(self) -> int: ...
    def end_depot(self) -> int: ...
    def fixed_vehicle_cost(self) -> int: ...
    def load(self) -> list[int]: ...
    def excess_load(self) -> list[int]: ...
    def excess_distance(self) -> int: ...
    def distance(self) -> int: ...
    def distance_cost(self) -> int: ...
    def unit_distance_cost(self) -> int: ...
    def has_distance_cost(self) -> bool: ...
    def duration(self) -> int: ...
    def overtime(self) -> int: ...
    def duration_cost(self) -> int: ...
    def unit_duration_cost(self) -> int: ...
    def unit_overtime_cost(self) -> int: ...
    def has_duration_cost(self) -> bool: ...
    def shift_duration(self) -> int: ...
    def max_duration(self) -> int: ...
    def max_overtime(self) -> int: ...
    def max_distance(self) -> int: ...
    def time_warp(self) -> int: ...
    def profile(self) -> int: ...
    def dist_at(self, idx: int, profile: int = 0) -> int: ...
    def dist_between(self, start: int, end: int, profile: int = 0) -> int: ...
    def dist_before(self, end: int) -> int: ...
    def dist_after(self, start: int) -> int: ...
    def load_at(self, idx: int, dimension: int = 0) -> LoadSegment: ...
    def load_between(
        self, start: int, end: int, dimension: int = 0
    ) -> LoadSegment: ...
    def load_before(self, end: int, dimension: int = 0) -> LoadSegment: ...
    def load_after(self, start: int, dimension: int = 0) -> LoadSegment: ...
    def duration_at(self, idx: int, profile: int = 0) -> DurationSegment: ...
    def duration_between(
        self, start: int, end: int, profile: int = 0
    ) -> DurationSegment: ...
    def duration_before(self, end: int) -> DurationSegment: ...
    def duration_after(self, start: int) -> DurationSegment: ...
    def append(self, node: Node) -> None: ...
    def clear(self) -> None: ...
    def insert(self, idx: int, node: Node) -> None: ...
    @staticmethod
    def swap(first: Node, second: Node) -> None: ...
    def update(self) -> None: ...

class Node:
    @overload
    def __init__(self, activity: Activity) -> None: ...
    @overload
    def __init__(self, type: ActivityType, idx: int) -> None: ...
    @overload
    def __init__(self, description: str) -> None: ...
    @property
    def activity(self) -> Activity: ...
    @property
    def idx(self) -> int: ...
    @property
    def type(self) -> ActivityType: ...
    @property
    def pos(self) -> int: ...
    @property
    def trip(self) -> int: ...
    @property
    def route(self) -> Route | None: ...
    def is_client(self) -> bool: ...
    def is_depot(self) -> bool: ...
    def is_start_depot(self) -> bool: ...
    def is_end_depot(self) -> bool: ...
    def is_reload_depot(self) -> bool: ...

class NeighbourhoodParams:
    weight_wait_time: float
    num_neighbours: int
    symmetric_proximity: bool
    def __init__(
        self,
        weight_wait_time: float = 0.2,
        num_neighbours: int = 50,
        symmetric_proximity: bool = True,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...

def compute_neighbours(
    data: ProblemData,
    params: NeighbourhoodParams,
) -> list[list[int]]: ...
